### ISSUE TITLE
Session - should Drop call Session::terminate?

### ISSUE THREAD

**Issue by jabedude** [jonhoo/openssh-rs#8] opened 2020-05-19 15:45 UTC
Hey there! I've been looking for a project like this, it looks awesome!

I was wondering if the Drop implementation for Session should call `Session::close` or `Session::terminate`. I noticed that the `tsp` example has a manual `session.close()` in it, would it be more "rusty" to take advantage of RAII instead?

**Comment by jonhoo** [comment] 2020-05-19 15:51
Ah, so, this is complicated.

First and foremost, `Session` [_does_](https://github.com/jonhoo/openssh-rs/blob/3b8f1632261286fca69bbed82bc5b184046750ac/src/lib.rs#L339) in fact terminate on `Drop`. The reason you want to manually call `close` is to surface any errors that may have occurred (which are silently ignored by `Drop`), and so that you can avoid running synchronous code inside of async code (the implementation of `Drop` is synchronous). This is documented, albeit a bit tersely, in the [docs for `Session`](https://docs.rs/openssh/0.5.2/openssh/struct.Session.html).

Which brings me to the second point: Rust does not currently have a good way to invoke asynchronous code (like `Session::close`) upon destruction, because `Drop` is synchronous. What's needed to be able to reliably use the RAII pattern in asynchronous code is an asynchronous version of `Drop`. The problem is described in some detail in [this article](https://boats.gitlab.io/blog/post/poll-drop/), and discussed at length [here](https://internals.rust-lang.org/t/asynchronous-destructors/11127).

With all that said, I _think_ `openssh` does everything it can here. It has a synchronous fallback drop that swallows errors, and then it exposes a "nice" async destructor that the caller can choose to use. So, I think we can probably close this issue. If you want to submit a PR that updates the docs to make this behavior clearer, that'd be awesome!

**Closed by jonhoo** 2020-05-19 15:51 UTC
